using System.Text.Json;
using AgentLedger.Core.AgentEventReceiptAggregate;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace AgentLedger.Infrastructure.Data.Config;

// Storage decisions: ADR 0009 (types, naming, timestamps) and ADR 0010 (receipts, duplicates allowed).
public sealed class AgentEventReceiptConfiguration : IEntityTypeConfiguration<AgentEventReceipt>
{
  public void Configure(EntityTypeBuilder<AgentEventReceipt> builder)
  {
    builder.ToTable("agent_event_receipts");

    builder.HasKey(e => e.Id);
    builder.Property(e => e.Id)
      .HasVogenConversion()
      .ValueGeneratedNever(); // generated by the ingest use case

    // The agent event's business key: the same for every resend, so not unique here.
    builder.Property(e => e.EventId)
      .HasVogenConversion()
      .IsRequired();

    // Stored by name so rows are readable in SQL; names must never change once stored.
    builder.Property(e => e.Agent)
      .HasConversion(agent => agent.Name, name => AgentKind.FromName(name, false))
      .IsRequired();

    builder.Property(e => e.EventType).IsRequired();
    builder.Property(e => e.NativeSessionId);
    builder.Property(e => e.CapturedAt).IsRequired();
    builder.Property(e => e.ReceivedAt).IsRequired();

    builder.ComplexProperty(e => e.Context);

    builder.Property(e => e.Tags)
      .HasColumnType("jsonb")
      .HasConversion(
        tags => JsonSerializer.Serialize(tags, JsonSerializerOptions.Default),
        json => JsonSerializer.Deserialize<Dictionary<string, string>>(json, JsonSerializerOptions.Default)!,
        new ValueComparer<IReadOnlyDictionary<string, string>>(
          (a, b) => a!.Count == b!.Count && !a.Except(b).Any(),
          tags => tags.Aggregate(0, (hash, tag) => HashCode.Combine(hash, tag.Key, tag.Value)),
          tags => new Dictionary<string, string>(tags)))
      .IsRequired();

    // json, not jsonb: keeps the payload byte-for-byte.
    builder.Property(e => e.Payload)
      .HasColumnType("json")
      .IsRequired();

    builder.HasIndex(e => e.EventId); // deduplication key for projections; deliberately not unique
    builder.HasIndex(e => new { e.Agent, e.NativeSessionId });
    builder.HasIndex(e => e.CapturedAt);
    // Incremental-processing watermark. Declared here too so the index can reference it;
    // AppDbContext adds the audit timestamps to every entity after configurations run.
    builder.Property<DateTimeOffset>(AppDbContext.UpdatedAt);
    builder.HasIndex(AppDbContext.UpdatedAt);
    builder.HasIndex(e => e.Tags).HasMethod("gin");
  }
}
