// <auto-generated />
using System;
using System.Collections.Generic;
using AgentLedger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentLedger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923234242_InitialAgentEvents")]
    partial class InitialAgentEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentLedger.Core.AgentEventAggregate.AgentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("NativeSessionId")
                        .HasColumnType("text")
                        .HasColumnName("native_session_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Context", "AgentLedger.Core.AgentEventAggregate.AgentEvent.Context#CaptureContext", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("GitBranch")
                                .HasColumnType("text")
                                .HasColumnName("context_git_branch");

                            b1.Property<string>("GitRepo")
                                .HasColumnType("text")
                                .HasColumnName("context_git_repo");

                            b1.Property<string>("GitWorktree")
                                .HasColumnType("text")
                                .HasColumnName("context_git_worktree");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("context_host");

                            b1.Property<string>("ProjectDir")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("context_project_dir");

                            b1.Property<string>("User")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("context_user");
                        });

                    b.HasKey("Id")
                        .HasName("pk_agent_events");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("ix_agent_events_captured_at");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_agent_events_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_agent_events_updated_at");

                    b.HasIndex("Agent", "NativeSessionId")
                        .HasDatabaseName("ix_agent_events_agent_native_session_id");

                    b.ToTable("agent_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
